// ─── Social Links ─────────────────────────────────────────────────────────────

export interface ArtistSocialLinks {
  instagram?: string;
  twitterX?: string;
  tiktok?: string;
  youtube?: string;
  facebook?: string;
  soundcloud?: string;
  spotify?: string;
  appleMusic?: string;
  website?: string;
}

// ─── Extended Artist Profile ─────────────────────────────────────────────────

export interface ArtistProfileWithSocials {
  id: string;
  bio: string;
  status: string;
  name: string;
  createdAt: bigint;
  socialLinks?: ArtistSocialLinks;
}

export type Language = "en" | "es" | "fr" | "pt" | "de" | "ja" | "ko" | "ar";

export interface LanguageOption {
  code: Language;
  label: string;
  nativeName: string;
}

export const LANGUAGES: LanguageOption[] = [
  { code: "en", label: "English", nativeName: "English" },
  { code: "es", label: "Spanish", nativeName: "Español" },
  { code: "fr", label: "French", nativeName: "Français" },
  { code: "pt", label: "Portuguese", nativeName: "Português" },
  { code: "de", label: "German", nativeName: "Deutsch" },
  { code: "ja", label: "Japanese", nativeName: "日本語" },
  { code: "ko", label: "Korean", nativeName: "한국어" },
  { code: "ar", label: "Arabic", nativeName: "العربية" },
];

export type TranslationKey =
  // Nav
  | "home"
  | "store"
  | "upload"
  | "dashboard"
  | "royalties"
  // Auth
  | "signIn"
  | "signOut"
  | "signUp"
  | "artistName"
  | "pinCode"
  | "createAccount"
  | "login"
  | "loginSubtitle"
  | "signupSubtitle"
  | "enterPin"
  | "confirmPin"
  | "nameLabel"
  | "pinLabel"
  | "loginBtn"
  | "signupBtn"
  | "noAccount"
  | "hasAccount"
  // Store
  | "storeTitle"
  | "storeSubtitle"
  | "searchPlaceholder"
  | "allGenres"
  | "buyNow"
  | "preview"
  | "addToCart"
  | "cart"
  | "checkout"
  | "cartEmpty"
  | "cartTotal"
  | "purchaseNow"
  | "liked"
  | "like"
  | "share"
  | "details"
  | "noTracks"
  | "loadingTracks"
  // Upload
  | "uploadTitle"
  | "uploadSubtitle"
  | "trackTitle"
  | "genre"
  | "price"
  | "releaseDate"
  | "explicit"
  | "preOrder"
  | "description"
  | "songDetails"
  | "coverArt"
  | "audioFile"
  | "uploadBtn"
  | "uploadingMsg"
  | "previewSelect"
  | "previewHelp"
  | "albumUpload"
  | "singleUpload"
  // Dashboard
  | "dashboardTitle"
  | "trackPreviews"
  | "totalListens"
  | "totalSales"
  | "grossRevenue"
  | "yourPayout"
  | "tracks"
  | "editTrack"
  | "deleteTrack"
  | "publishTrack"
  | "unpublishTrack"
  | "noTracks2"
  | "realTimeStats"
  // Royalties
  | "royaltiesTitle"
  | "availableBalance"
  | "requestPayout"
  | "payoutHistory"
  | "bankingInfo"
  | "accountHolder"
  | "bankName"
  | "routingNumber"
  | "accountNumber"
  | "saveBanking"
  | "periodStats"
  | "unitsSold"
  | "beforeSplit"
  | "payoutRate"
  // Admin
  | "adminTitle"
  | "adminArtists"
  | "suspend"
  | "unsuspend"
  | "delete"
  | "adminLogin"
  | "adminPinLabel"
  | "manageArtists"
  | "artistStatus"
  | "active"
  | "suspended"
  | "deleted"
  // Notifications
  | "notifications"
  | "noNotifications"
  | "artistJoined"
  | "newComment"
  | "trackUploaded"
  | "newSale"
  | "welcomeBack"
  | "thankYou"
  // Cart / Purchase flow
  | "yourCart"
  | "removeItem"
  | "proceedToCheckout"
  | "downloadNow"
  | "downloadReady"
  | "purchaseComplete"
  | "downloadPrompt"
  | "myPurchases"
  | "reDownload"
  | "expires"
  // Footer
  | "navigation"
  | "legal"
  | "support"
  | "stayInLoop"
  | "newsletterSubtitle"
  | "subscribe"
  | "termsOfService"
  | "privacyPolicy"
  | "cookiePolicy"
  | "dmca"
  | "royaltyPolicy"
  | "helpCenter"
  | "contactUs"
  | "fileComplaint"
  | "artistResources"
  | "distributionGuide"
  | "royaltyFaq"
  // Misc
  | "language"
  | "darkMode"
  | "loading"
  | "error"
  | "success"
  | "cancel"
  | "save"
  | "edit"
  | "close"
  | "back"
  | "next"
  | "confirm"
  | "yourArtistName"
  // Support Chat
  | "support_chat_title"
  | "support_chat_welcome"
  | "support_chat_placeholder"
  | "support_chat_send"
  | "support_chat_thinking"
  | "support_chat_error";

export type Translations = Record<TranslationKey, string>;

export const TRANSLATIONS: Record<Language, Translations> = {
  en: {
    home: "Home",
    store: "Store",
    upload: "Upload",
    dashboard: "Artist Dashboard",
    royalties: "Royalty Dashboard",
    signIn: "Sign In",
    signOut: "Sign Out",
    signUp: "Sign Up",
    artistName: "Artist Name",
    pinCode: "PIN Code",
    createAccount: "Create Account",
    login: "Log In",
    loginSubtitle: "Welcome back to Chosen One Productions",
    signupSubtitle: "Join Chosen One Productions Distribution",
    enterPin: "Enter your PIN",
    confirmPin: "Confirm PIN",
    nameLabel: "Your artist name",
    pinLabel: "4-6 digit PIN",
    loginBtn: "Log In",
    signupBtn: "Create Account",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    storeTitle: "Music Store",
    storeSubtitle: "Discover and support independent artists",
    searchPlaceholder: "Search songs, artists...",
    allGenres: "All Genres",
    buyNow: "Buy Now",
    preview: "Preview",
    addToCart: "Add to Cart",
    cart: "Cart",
    checkout: "Checkout",
    cartEmpty: "Your cart is empty",
    cartTotal: "Total",
    purchaseNow: "Purchase Now",
    liked: "Liked",
    like: "Like",
    share: "Share",
    details: "Details",
    noTracks: "No tracks found",
    loadingTracks: "Loading tracks...",
    uploadTitle: "Upload Music",
    uploadSubtitle: "Share your art with the world",
    trackTitle: "Track Title",
    genre: "Genre",
    price: "Price (USD)",
    releaseDate: "Release Date",
    explicit: "Explicit Content",
    preOrder: "Pre-Order",
    description: "Description",
    songDetails: "Song Details (optional)",
    coverArt: "Cover Art",
    audioFile: "Audio File (MP3 or WAV)",
    uploadBtn: "Upload Track",
    uploadingMsg: "Uploading...",
    previewSelect: "Select 30s Preview",
    previewHelp:
      "Click and drag on the waveform to choose your 30-second preview clip",
    albumUpload: "Album Upload",
    singleUpload: "Single Upload",
    dashboardTitle: "Artist Dashboard",
    trackPreviews: "Track Previews",
    totalListens: "Total Listens",
    totalSales: "Total Sales",
    grossRevenue: "Gross Revenue",
    yourPayout: "Your Payout",
    tracks: "My Tracks",
    editTrack: "Edit",
    deleteTrack: "Delete",
    publishTrack: "Publish",
    unpublishTrack: "Unpublish",
    noTracks2: "No tracks yet — upload your first song!",
    realTimeStats: "Real-Time Analytics",
    royaltiesTitle: "Royalty Dashboard",
    availableBalance: "Available Balance",
    requestPayout: "Request Payout",
    payoutHistory: "Payout History",
    bankingInfo: "Banking Information",
    accountHolder: "Account Holder Name",
    bankName: "Bank Name",
    routingNumber: "Routing Number",
    accountNumber: "Account Number",
    saveBanking: "Save Banking Info",
    periodStats: "Period Stats",
    unitsSold: "Units Sold",
    beforeSplit: "Before Split",
    payoutRate: "85% Artist Payout",
    adminTitle: "Admin Panel",
    adminArtists: "Manage Artists",
    suspend: "Suspend",
    unsuspend: "Unsuspend",
    delete: "Delete",
    adminLogin: "Admin Login",
    adminPinLabel: "Admin PIN",
    manageArtists: "Artist Management",
    artistStatus: "Status",
    active: "Active",
    suspended: "Suspended",
    deleted: "Deleted",
    notifications: "Notifications",
    noNotifications: "No new notifications",
    artistJoined: "A new artist has joined!",
    newComment: "New comment on your store",
    trackUploaded: "New track uploaded",
    newSale: "New sale!",
    welcomeBack: "Welcome Back",
    thankYou: "Thank You! 👑",
    yourCart: "Your Cart",
    removeItem: "Remove",
    proceedToCheckout: "Proceed to Checkout",
    downloadNow: "Download Now",
    downloadReady: "Your download is ready!",
    purchaseComplete: "Purchase Complete!",
    downloadPrompt: "Download your purchased songs below",
    myPurchases: "My Purchases",
    reDownload: "Re-Download",
    expires: "Expires",
    navigation: "Navigation",
    legal: "Legal",
    support: "Support",
    stayInLoop: "🎵 Stay in the loop",
    newsletterSubtitle:
      "New releases, royalty tips, and artist features — straight to your inbox.",
    subscribe: "Subscribe",
    termsOfService: "Terms of Service",
    privacyPolicy: "Privacy Policy",
    cookiePolicy: "Cookie Policy",
    dmca: "DMCA",
    royaltyPolicy: "Royalty Policy",
    helpCenter: "Help Center",
    contactUs: "Contact Us",
    fileComplaint: "File a Complaint",
    artistResources: "Artist Resources",
    distributionGuide: "Distribution Guide",
    royaltyFaq: "Royalty FAQ",
    language: "Language",
    darkMode: "Dark Mode",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    cancel: "Cancel",
    save: "Save",
    edit: "Edit",
    close: "Close",
    back: "Back",
    next: "Next",
    confirm: "Confirm",
    yourArtistName: "Your Artist Name",
    support_chat_title: "Chosen One Support",
    support_chat_welcome:
      "Hi! I'm your support assistant. Ask me about uploading, purchasing, downloading, payments, accounts, or royalties.",
    support_chat_placeholder: "Type your question...",
    support_chat_send: "Send",
    support_chat_thinking: "Thinking...",
    support_chat_error:
      "I'm having trouble connecting. Please try again or visit our Help Center.",
  },
  es: {
    home: "Inicio",
    store: "Tienda",
    upload: "Subir",
    dashboard: "Panel del Artista",
    royalties: "Panel de Regalías",
    signIn: "Iniciar Sesión",
    signOut: "Cerrar Sesión",
    signUp: "Registrarse",
    artistName: "Nombre Artístico",
    pinCode: "Código PIN",
    createAccount: "Crear Cuenta",
    login: "Iniciar Sesión",
    loginSubtitle: "Bienvenido a Chosen One Productions",
    signupSubtitle: "Únete a Chosen One Productions Distribution",
    enterPin: "Ingresa tu PIN",
    confirmPin: "Confirmar PIN",
    nameLabel: "Tu nombre artístico",
    pinLabel: "PIN de 4-6 dígitos",
    loginBtn: "Iniciar Sesión",
    signupBtn: "Crear Cuenta",
    noAccount: "¿No tienes cuenta?",
    hasAccount: "¿Ya tienes cuenta?",
    storeTitle: "Tienda de Música",
    storeSubtitle: "Descubre y apoya artistas independientes",
    searchPlaceholder: "Buscar canciones, artistas...",
    allGenres: "Todos los Géneros",
    buyNow: "Comprar Ahora",
    preview: "Vista Previa",
    addToCart: "Agregar al Carrito",
    cart: "Carrito",
    checkout: "Pagar",
    cartEmpty: "Tu carrito está vacío",
    cartTotal: "Total",
    purchaseNow: "Comprar Ahora",
    liked: "Me Gusta",
    like: "Me Gusta",
    share: "Compartir",
    details: "Detalles",
    noTracks: "No se encontraron pistas",
    loadingTracks: "Cargando pistas...",
    uploadTitle: "Subir Música",
    uploadSubtitle: "Comparte tu arte con el mundo",
    trackTitle: "Título de la Pista",
    genre: "Género",
    price: "Precio (USD)",
    releaseDate: "Fecha de Lanzamiento",
    explicit: "Contenido Explícito",
    preOrder: "Pre-Orden",
    description: "Descripción",
    songDetails: "Detalles de la Canción (opcional)",
    coverArt: "Arte de Portada",
    audioFile: "Archivo de Audio (MP3 o WAV)",
    uploadBtn: "Subir Pista",
    uploadingMsg: "Subiendo...",
    previewSelect: "Seleccionar Vista Previa de 30s",
    previewHelp:
      "Haz clic y arrastra en la forma de onda para elegir tu clip de vista previa de 30 segundos",
    albumUpload: "Subir Álbum",
    singleUpload: "Subir Single",
    dashboardTitle: "Panel del Artista",
    trackPreviews: "Vistas Previas de Pistas",
    totalListens: "Total de Escuchas",
    totalSales: "Ventas Totales",
    grossRevenue: "Ingresos Brutos",
    yourPayout: "Tu Pago",
    tracks: "Mis Pistas",
    editTrack: "Editar",
    deleteTrack: "Eliminar",
    publishTrack: "Publicar",
    unpublishTrack: "Despublicar",
    noTracks2: "Aún no hay pistas — ¡sube tu primera canción!",
    realTimeStats: "Análisis en Tiempo Real",
    royaltiesTitle: "Panel de Regalías",
    availableBalance: "Saldo Disponible",
    requestPayout: "Solicitar Pago",
    payoutHistory: "Historial de Pagos",
    bankingInfo: "Información Bancaria",
    accountHolder: "Titular de la Cuenta",
    bankName: "Nombre del Banco",
    routingNumber: "Número de Ruta",
    accountNumber: "Número de Cuenta",
    saveBanking: "Guardar Información Bancaria",
    periodStats: "Estadísticas del Período",
    unitsSold: "Unidades Vendidas",
    beforeSplit: "Antes del Reparto",
    payoutRate: "85% Pago al Artista",
    adminTitle: "Panel de Administración",
    adminArtists: "Gestionar Artistas",
    suspend: "Suspender",
    unsuspend: "Reactivar",
    delete: "Eliminar",
    adminLogin: "Inicio de Sesión Admin",
    adminPinLabel: "PIN Admin",
    manageArtists: "Gestión de Artistas",
    artistStatus: "Estado",
    active: "Activo",
    suspended: "Suspendido",
    deleted: "Eliminado",
    notifications: "Notificaciones",
    noNotifications: "Sin notificaciones nuevas",
    artistJoined: "¡Un nuevo artista se ha unido!",
    newComment: "Nuevo comentario en tu tienda",
    trackUploaded: "Nueva pista subida",
    newSale: "¡Nueva venta!",
    welcomeBack: "Bienvenido de Nuevo",
    thankYou: "¡Gracias! 👑",
    yourCart: "Tu Carrito",
    removeItem: "Eliminar",
    proceedToCheckout: "Proceder al Pago",
    downloadNow: "Descargar Ahora",
    downloadReady: "¡Tu descarga está lista!",
    purchaseComplete: "¡Compra Completada!",
    downloadPrompt: "Descarga tus canciones compradas a continuación",
    myPurchases: "Mis Compras",
    reDownload: "Re-Descargar",
    expires: "Expira",
    navigation: "Navegación",
    legal: "Legal",
    support: "Soporte",
    stayInLoop: "🎵 Mantente informado",
    newsletterSubtitle:
      "Nuevos lanzamientos, consejos de regalías y más — directo a tu bandeja de entrada.",
    subscribe: "Suscribirse",
    termsOfService: "Términos de Servicio",
    privacyPolicy: "Política de Privacidad",
    cookiePolicy: "Política de Cookies",
    dmca: "DMCA",
    royaltyPolicy: "Política de Regalías",
    helpCenter: "Centro de Ayuda",
    contactUs: "Contáctanos",
    fileComplaint: "Presentar una Queja",
    artistResources: "Recursos para Artistas",
    distributionGuide: "Guía de Distribución",
    royaltyFaq: "Preguntas Frecuentes de Regalías",
    language: "Idioma",
    darkMode: "Modo Oscuro",
    loading: "Cargando...",
    error: "Error",
    success: "Éxito",
    cancel: "Cancelar",
    save: "Guardar",
    edit: "Editar",
    close: "Cerrar",
    back: "Volver",
    next: "Siguiente",
    confirm: "Confirmar",
    yourArtistName: "Tu Nombre Artístico",
    support_chat_title: "Soporte Chosen One",
    support_chat_welcome:
      "¡Hola! Soy tu asistente de soporte. Pregúntame sobre cargas, compras, descargas, pagos, cuentas o regalías.",
    support_chat_placeholder: "Escribe tu pregunta...",
    support_chat_send: "Enviar",
    support_chat_thinking: "Pensando...",
    support_chat_error:
      "Tengo problemas para conectarme. Por favor intenta de nuevo o visita nuestro Centro de Ayuda.",
  },
  fr: {
    home: "Accueil",
    store: "Boutique",
    upload: "Télécharger",
    dashboard: "Tableau de Bord Artiste",
    royalties: "Tableau de Bord Redevances",
    signIn: "Se Connecter",
    signOut: "Se Déconnecter",
    signUp: "S'inscrire",
    artistName: "Nom d'Artiste",
    pinCode: "Code PIN",
    createAccount: "Créer un Compte",
    login: "Se Connecter",
    loginSubtitle: "Bienvenue sur Chosen One Productions",
    signupSubtitle: "Rejoignez Chosen One Productions Distribution",
    enterPin: "Entrez votre PIN",
    confirmPin: "Confirmer le PIN",
    nameLabel: "Votre nom d'artiste",
    pinLabel: "PIN de 4 à 6 chiffres",
    loginBtn: "Se Connecter",
    signupBtn: "Créer un Compte",
    noAccount: "Pas de compte?",
    hasAccount: "Déjà un compte?",
    storeTitle: "Boutique Musicale",
    storeSubtitle: "Découvrez et soutenez les artistes indépendants",
    searchPlaceholder: "Rechercher chansons, artistes...",
    allGenres: "Tous les Genres",
    buyNow: "Acheter Maintenant",
    preview: "Aperçu",
    addToCart: "Ajouter au Panier",
    cart: "Panier",
    checkout: "Payer",
    cartEmpty: "Votre panier est vide",
    cartTotal: "Total",
    purchaseNow: "Acheter Maintenant",
    liked: "Aimé",
    like: "J'aime",
    share: "Partager",
    details: "Détails",
    noTracks: "Aucune piste trouvée",
    loadingTracks: "Chargement des pistes...",
    uploadTitle: "Télécharger de la Musique",
    uploadSubtitle: "Partagez votre art avec le monde",
    trackTitle: "Titre de la Piste",
    genre: "Genre",
    price: "Prix (USD)",
    releaseDate: "Date de Sortie",
    explicit: "Contenu Explicite",
    preOrder: "Pré-commande",
    description: "Description",
    songDetails: "Détails de la Chanson (optionnel)",
    coverArt: "Pochette",
    audioFile: "Fichier Audio (MP3 ou WAV)",
    uploadBtn: "Télécharger la Piste",
    uploadingMsg: "Téléchargement...",
    previewSelect: "Sélectionner Aperçu 30s",
    previewHelp:
      "Cliquez et faites glisser sur la forme d'onde pour choisir votre clip de 30 secondes",
    albumUpload: "Télécharger un Album",
    singleUpload: "Télécharger un Single",
    dashboardTitle: "Tableau de Bord Artiste",
    trackPreviews: "Aperçus des Pistes",
    totalListens: "Total des Écoutes",
    totalSales: "Ventes Totales",
    grossRevenue: "Revenus Bruts",
    yourPayout: "Votre Paiement",
    tracks: "Mes Pistes",
    editTrack: "Modifier",
    deleteTrack: "Supprimer",
    publishTrack: "Publier",
    unpublishTrack: "Dépublier",
    noTracks2: "Pas encore de pistes — téléchargez votre première chanson!",
    realTimeStats: "Analyses en Temps Réel",
    royaltiesTitle: "Tableau de Bord Redevances",
    availableBalance: "Solde Disponible",
    requestPayout: "Demander un Paiement",
    payoutHistory: "Historique des Paiements",
    bankingInfo: "Informations Bancaires",
    accountHolder: "Titulaire du Compte",
    bankName: "Nom de la Banque",
    routingNumber: "Numéro de Routage",
    accountNumber: "Numéro de Compte",
    saveBanking: "Enregistrer les Informations Bancaires",
    periodStats: "Stats de la Période",
    unitsSold: "Unités Vendues",
    beforeSplit: "Avant Partage",
    payoutRate: "85% Paiement Artiste",
    adminTitle: "Panneau d'Administration",
    adminArtists: "Gérer les Artistes",
    suspend: "Suspendre",
    unsuspend: "Réactiver",
    delete: "Supprimer",
    adminLogin: "Connexion Admin",
    adminPinLabel: "PIN Admin",
    manageArtists: "Gestion des Artistes",
    artistStatus: "Statut",
    active: "Actif",
    suspended: "Suspendu",
    deleted: "Supprimé",
    notifications: "Notifications",
    noNotifications: "Pas de nouvelles notifications",
    artistJoined: "Un nouvel artiste vient de rejoindre!",
    newComment: "Nouveau commentaire sur votre boutique",
    trackUploaded: "Nouvelle piste téléchargée",
    newSale: "Nouvelle vente!",
    welcomeBack: "Bienvenue",
    thankYou: "Merci! 👑",
    yourCart: "Votre Panier",
    removeItem: "Supprimer",
    proceedToCheckout: "Passer à la Caisse",
    downloadNow: "Télécharger Maintenant",
    downloadReady: "Votre téléchargement est prêt!",
    purchaseComplete: "Achat Terminé!",
    downloadPrompt: "Téléchargez vos chansons achetées ci-dessous",
    myPurchases: "Mes Achats",
    reDownload: "Re-Télécharger",
    expires: "Expire",
    navigation: "Navigation",
    legal: "Légal",
    support: "Support",
    stayInLoop: "🎵 Restez informé",
    newsletterSubtitle:
      "Nouvelles sorties, conseils sur les redevances et plus — directement dans votre boîte de réception.",
    subscribe: "S'abonner",
    termsOfService: "Conditions d'Utilisation",
    privacyPolicy: "Politique de Confidentialité",
    cookiePolicy: "Politique des Cookies",
    dmca: "DMCA",
    royaltyPolicy: "Politique de Redevances",
    helpCenter: "Centre d'Aide",
    contactUs: "Contactez-nous",
    fileComplaint: "Déposer une Plainte",
    artistResources: "Ressources Artistes",
    distributionGuide: "Guide de Distribution",
    royaltyFaq: "FAQ Redevances",
    language: "Langue",
    darkMode: "Mode Sombre",
    loading: "Chargement...",
    error: "Erreur",
    success: "Succès",
    cancel: "Annuler",
    save: "Enregistrer",
    edit: "Modifier",
    close: "Fermer",
    back: "Retour",
    next: "Suivant",
    confirm: "Confirmer",
    yourArtistName: "Votre Nom d'Artiste",
    support_chat_title: "Support Chosen One",
    support_chat_welcome:
      "Salut ! Je suis votre assistant de support. Posez-moi des questions sur les téléchargements, les achats, les paiements, les comptes ou les redevances.",
    support_chat_placeholder: "Tapez votre question...",
    support_chat_send: "Envoyer",
    support_chat_thinking: "En train de réfléchir...",
    support_chat_error:
      "J'ai des difficultés à me connecter. Veuillez réessayer ou visitez notre Centre d'Aide.",
  },
  pt: {
    home: "Início",
    store: "Loja",
    upload: "Enviar",
    dashboard: "Painel do Artista",
    royalties: "Painel de Royalties",
    signIn: "Entrar",
    signOut: "Sair",
    signUp: "Cadastrar",
    artistName: "Nome Artístico",
    pinCode: "Código PIN",
    createAccount: "Criar Conta",
    login: "Entrar",
    loginSubtitle: "Bem-vindo à Chosen One Productions",
    signupSubtitle: "Junte-se à Chosen One Productions Distribution",
    enterPin: "Digite seu PIN",
    confirmPin: "Confirmar PIN",
    nameLabel: "Seu nome artístico",
    pinLabel: "PIN de 4-6 dígitos",
    loginBtn: "Entrar",
    signupBtn: "Criar Conta",
    noAccount: "Não tem conta?",
    hasAccount: "Já tem conta?",
    storeTitle: "Loja de Música",
    storeSubtitle: "Descubra e apoie artistas independentes",
    searchPlaceholder: "Buscar músicas, artistas...",
    allGenres: "Todos os Gêneros",
    buyNow: "Comprar Agora",
    preview: "Pré-visualização",
    addToCart: "Adicionar ao Carrinho",
    cart: "Carrinho",
    checkout: "Finalizar Compra",
    cartEmpty: "Seu carrinho está vazio",
    cartTotal: "Total",
    purchaseNow: "Comprar Agora",
    liked: "Curtido",
    like: "Curtir",
    share: "Compartilhar",
    details: "Detalhes",
    noTracks: "Nenhuma faixa encontrada",
    loadingTracks: "Carregando faixas...",
    uploadTitle: "Enviar Música",
    uploadSubtitle: "Compartilhe sua arte com o mundo",
    trackTitle: "Título da Faixa",
    genre: "Gênero",
    price: "Preço (USD)",
    releaseDate: "Data de Lançamento",
    explicit: "Conteúdo Explícito",
    preOrder: "Pré-venda",
    description: "Descrição",
    songDetails: "Detalhes da Música (opcional)",
    coverArt: "Arte da Capa",
    audioFile: "Arquivo de Áudio (MP3 ou WAV)",
    uploadBtn: "Enviar Faixa",
    uploadingMsg: "Enviando...",
    previewSelect: "Selecionar Prévia de 30s",
    previewHelp:
      "Clique e arraste na forma de onda para escolher seu clipe de prévia de 30 segundos",
    albumUpload: "Enviar Álbum",
    singleUpload: "Enviar Single",
    dashboardTitle: "Painel do Artista",
    trackPreviews: "Prévias de Faixas",
    totalListens: "Total de Ouvidas",
    totalSales: "Vendas Totais",
    grossRevenue: "Receita Bruta",
    yourPayout: "Seu Pagamento",
    tracks: "Minhas Faixas",
    editTrack: "Editar",
    deleteTrack: "Excluir",
    publishTrack: "Publicar",
    unpublishTrack: "Despublicar",
    noTracks2: "Ainda sem faixas — envie sua primeira música!",
    realTimeStats: "Análises em Tempo Real",
    royaltiesTitle: "Painel de Royalties",
    availableBalance: "Saldo Disponível",
    requestPayout: "Solicitar Pagamento",
    payoutHistory: "Histórico de Pagamentos",
    bankingInfo: "Informações Bancárias",
    accountHolder: "Titular da Conta",
    bankName: "Nome do Banco",
    routingNumber: "Número de Roteamento",
    accountNumber: "Número da Conta",
    saveBanking: "Salvar Informações Bancárias",
    periodStats: "Estatísticas do Período",
    unitsSold: "Unidades Vendidas",
    beforeSplit: "Antes da Divisão",
    payoutRate: "85% de Pagamento ao Artista",
    adminTitle: "Painel Administrativo",
    adminArtists: "Gerenciar Artistas",
    suspend: "Suspender",
    unsuspend: "Reativar",
    delete: "Excluir",
    adminLogin: "Login Admin",
    adminPinLabel: "PIN Admin",
    manageArtists: "Gerenciamento de Artistas",
    artistStatus: "Status",
    active: "Ativo",
    suspended: "Suspenso",
    deleted: "Excluído",
    notifications: "Notificações",
    noNotifications: "Sem novas notificações",
    artistJoined: "Um novo artista entrou!",
    newComment: "Novo comentário na sua loja",
    trackUploaded: "Nova faixa enviada",
    newSale: "Nova venda!",
    welcomeBack: "Bem-vindo de Volta",
    thankYou: "Obrigado! 👑",
    yourCart: "Seu Carrinho",
    removeItem: "Remover",
    proceedToCheckout: "Finalizar Compra",
    downloadNow: "Baixar Agora",
    downloadReady: "Seu download está pronto!",
    purchaseComplete: "Compra Concluída!",
    downloadPrompt: "Baixe suas músicas compradas abaixo",
    myPurchases: "Minhas Compras",
    reDownload: "Re-Baixar",
    expires: "Expira",
    navigation: "Navegação",
    legal: "Legal",
    support: "Suporte",
    stayInLoop: "🎵 Fique por dentro",
    newsletterSubtitle:
      "Novos lançamentos, dicas de royalties e mais — direto na sua caixa de entrada.",
    subscribe: "Assinar",
    termsOfService: "Termos de Serviço",
    privacyPolicy: "Política de Privacidade",
    cookiePolicy: "Política de Cookies",
    dmca: "DMCA",
    royaltyPolicy: "Política de Royalties",
    helpCenter: "Central de Ajuda",
    contactUs: "Entre em Contato",
    fileComplaint: "Registrar Reclamação",
    artistResources: "Recursos para Artistas",
    distributionGuide: "Guia de Distribuição",
    royaltyFaq: "FAQ de Royalties",
    language: "Idioma",
    darkMode: "Modo Escuro",
    loading: "Carregando...",
    error: "Erro",
    success: "Sucesso",
    cancel: "Cancelar",
    save: "Salvar",
    edit: "Editar",
    close: "Fechar",
    back: "Voltar",
    next: "Próximo",
    confirm: "Confirmar",
    yourArtistName: "Seu Nome Artístico",
    support_chat_title: "Suporte Chosen One",
    support_chat_welcome:
      "Olá! Sou seu assistente de suporte. Pergunte-me sobre envios, compras, downloads, pagamentos, contas ou royalties.",
    support_chat_placeholder: "Digite sua pergunta...",
    support_chat_send: "Enviar",
    support_chat_thinking: "Pensando...",
    support_chat_error:
      "Estou com problemas de conexão. Por favor, tente novamente ou visite nossa Central de Ajuda.",
  },
  de: {
    home: "Startseite",
    store: "Shop",
    upload: "Hochladen",
    dashboard: "Künstler-Dashboard",
    royalties: "Lizenzgebühren-Dashboard",
    signIn: "Anmelden",
    signOut: "Abmelden",
    signUp: "Registrieren",
    artistName: "Künstlername",
    pinCode: "PIN-Code",
    createAccount: "Konto Erstellen",
    login: "Anmelden",
    loginSubtitle: "Willkommen bei Chosen One Productions",
    signupSubtitle: "Tritt Chosen One Productions Distribution bei",
    enterPin: "PIN eingeben",
    confirmPin: "PIN bestätigen",
    nameLabel: "Dein Künstlername",
    pinLabel: "4-6-stellige PIN",
    loginBtn: "Anmelden",
    signupBtn: "Konto Erstellen",
    noAccount: "Kein Konto?",
    hasAccount: "Schon ein Konto?",
    storeTitle: "Musikshop",
    storeSubtitle: "Entdecke und unterstütze unabhängige Künstler",
    searchPlaceholder: "Songs, Künstler suchen...",
    allGenres: "Alle Genres",
    buyNow: "Jetzt Kaufen",
    preview: "Vorschau",
    addToCart: "In den Warenkorb",
    cart: "Warenkorb",
    checkout: "Kasse",
    cartEmpty: "Dein Warenkorb ist leer",
    cartTotal: "Gesamt",
    purchaseNow: "Jetzt Kaufen",
    liked: "Gefällt mir",
    like: "Gefällt mir",
    share: "Teilen",
    details: "Details",
    noTracks: "Keine Tracks gefunden",
    loadingTracks: "Tracks werden geladen...",
    uploadTitle: "Musik Hochladen",
    uploadSubtitle: "Teile deine Kunst mit der Welt",
    trackTitle: "Track-Titel",
    genre: "Genre",
    price: "Preis (USD)",
    releaseDate: "Erscheinungsdatum",
    explicit: "Expliziter Inhalt",
    preOrder: "Vorbestellung",
    description: "Beschreibung",
    songDetails: "Song-Details (optional)",
    coverArt: "Cover-Art",
    audioFile: "Audiodatei (MP3 oder WAV)",
    uploadBtn: "Track Hochladen",
    uploadingMsg: "Lädt hoch...",
    previewSelect: "30s-Vorschau Auswählen",
    previewHelp:
      "Klicke und ziehe auf der Wellenform, um deinen 30-Sekunden-Vorschauclip auszuwählen",
    albumUpload: "Album Hochladen",
    singleUpload: "Single Hochladen",
    dashboardTitle: "Künstler-Dashboard",
    trackPreviews: "Track-Vorschauen",
    totalListens: "Gesamtaufrufe",
    totalSales: "Gesamtverkäufe",
    grossRevenue: "Bruttoeinnahmen",
    yourPayout: "Deine Auszahlung",
    tracks: "Meine Tracks",
    editTrack: "Bearbeiten",
    deleteTrack: "Löschen",
    publishTrack: "Veröffentlichen",
    unpublishTrack: "Unveröffentlichen",
    noTracks2: "Noch keine Tracks — lade deinen ersten Song hoch!",
    realTimeStats: "Echtzeit-Analysen",
    royaltiesTitle: "Lizenzgebühren-Dashboard",
    availableBalance: "Verfügbares Guthaben",
    requestPayout: "Auszahlung Anfordern",
    payoutHistory: "Auszahlungshistorie",
    bankingInfo: "Bankdaten",
    accountHolder: "Kontoinhaber",
    bankName: "Bankname",
    routingNumber: "Bankleitzahl",
    accountNumber: "Kontonummer",
    saveBanking: "Bankdaten Speichern",
    periodStats: "Periodenstatistiken",
    unitsSold: "Verkaufte Einheiten",
    beforeSplit: "Vor Aufteilung",
    payoutRate: "85% Künstlerauszahlung",
    adminTitle: "Admin-Panel",
    adminArtists: "Künstler Verwalten",
    suspend: "Sperren",
    unsuspend: "Entsperren",
    delete: "Löschen",
    adminLogin: "Admin-Anmeldung",
    adminPinLabel: "Admin-PIN",
    manageArtists: "Künstlerverwaltung",
    artistStatus: "Status",
    active: "Aktiv",
    suspended: "Gesperrt",
    deleted: "Gelöscht",
    notifications: "Benachrichtigungen",
    noNotifications: "Keine neuen Benachrichtigungen",
    artistJoined: "Ein neuer Künstler ist beigetreten!",
    newComment: "Neuer Kommentar in deinem Shop",
    trackUploaded: "Neuer Track hochgeladen",
    newSale: "Neuer Verkauf!",
    welcomeBack: "Willkommen Zurück",
    thankYou: "Danke! 👑",
    yourCart: "Dein Warenkorb",
    removeItem: "Entfernen",
    proceedToCheckout: "Zur Kasse",
    downloadNow: "Jetzt Herunterladen",
    downloadReady: "Dein Download ist bereit!",
    purchaseComplete: "Kauf Abgeschlossen!",
    downloadPrompt: "Lade deine gekauften Songs unten herunter",
    myPurchases: "Meine Käufe",
    reDownload: "Erneut Herunterladen",
    expires: "Läuft ab",
    navigation: "Navigation",
    legal: "Rechtliches",
    support: "Support",
    stayInLoop: "🎵 Bleib informiert",
    newsletterSubtitle:
      "Neue Releases, Royalty-Tipps und mehr — direkt in deine Inbox.",
    subscribe: "Abonnieren",
    termsOfService: "Nutzungsbedingungen",
    privacyPolicy: "Datenschutzrichtlinie",
    cookiePolicy: "Cookie-Richtlinie",
    dmca: "DMCA",
    royaltyPolicy: "Lizenzgebühren-Richtlinie",
    helpCenter: "Hilfecenter",
    contactUs: "Kontaktiere uns",
    fileComplaint: "Beschwerde Einreichen",
    artistResources: "Künstlerressourcen",
    distributionGuide: "Vertriebshandbuch",
    royaltyFaq: "Lizenzgebühren-FAQ",
    language: "Sprache",
    darkMode: "Dunkelmodus",
    loading: "Lädt...",
    error: "Fehler",
    success: "Erfolg",
    cancel: "Abbrechen",
    save: "Speichern",
    edit: "Bearbeiten",
    close: "Schließen",
    back: "Zurück",
    next: "Weiter",
    confirm: "Bestätigen",
    yourArtistName: "Dein Künstlername",
    support_chat_title: "Chosen One Support",
    support_chat_welcome:
      "Hallo! Ich bin dein Support-Assistent. Frag mich zu Uploads, Käufen, Downloads, Zahlungen, Konten oder Lizenzgebühren.",
    support_chat_placeholder: "Schreib deine Frage...",
    support_chat_send: "Senden",
    support_chat_thinking: "Nachdenken...",
    support_chat_error:
      "Ich habe Verbindungsprobleme. Bitte versuche es erneut oder besuche unser Hilfecenter.",
  },
  ja: {
    home: "ホーム",
    store: "ストア",
    upload: "アップロード",
    dashboard: "アーティストダッシュボード",
    royalties: "ロイヤリティダッシュボード",
    signIn: "ログイン",
    signOut: "ログアウト",
    signUp: "登録",
    artistName: "アーティスト名",
    pinCode: "PINコード",
    createAccount: "アカウント作成",
    login: "ログイン",
    loginSubtitle: "Chosen One Productionsへようこそ",
    signupSubtitle: "Chosen One Productions Distributionに参加",
    enterPin: "PINを入力",
    confirmPin: "PINを確認",
    nameLabel: "アーティスト名",
    pinLabel: "4〜6桁のPIN",
    loginBtn: "ログイン",
    signupBtn: "アカウント作成",
    noAccount: "アカウントをお持ちでないですか？",
    hasAccount: "すでにアカウントをお持ちですか？",
    storeTitle: "ミュージックストア",
    storeSubtitle: "インディーズアーティストを発見してサポート",
    searchPlaceholder: "曲、アーティストを検索...",
    allGenres: "全ジャンル",
    buyNow: "今すぐ購入",
    preview: "プレビュー",
    addToCart: "カートに追加",
    cart: "カート",
    checkout: "チェックアウト",
    cartEmpty: "カートは空です",
    cartTotal: "合計",
    purchaseNow: "今すぐ購入",
    liked: "いいね済み",
    like: "いいね",
    share: "シェア",
    details: "詳細",
    noTracks: "トラックが見つかりません",
    loadingTracks: "トラックを読み込み中...",
    uploadTitle: "音楽をアップロード",
    uploadSubtitle: "あなたのアートを世界と共有",
    trackTitle: "トラックタイトル",
    genre: "ジャンル",
    price: "価格 (USD)",
    releaseDate: "リリース日",
    explicit: "露骨なコンテンツ",
    preOrder: "予約注文",
    description: "説明",
    songDetails: "曲の詳細 (任意)",
    coverArt: "カバーアート",
    audioFile: "オーディオファイル (MP3またはWAV)",
    uploadBtn: "トラックをアップロード",
    uploadingMsg: "アップロード中...",
    previewSelect: "30秒プレビューを選択",
    previewHelp:
      "波形をクリックしてドラッグし、30秒のプレビュークリップを選択してください",
    albumUpload: "アルバムアップロード",
    singleUpload: "シングルアップロード",
    dashboardTitle: "アーティストダッシュボード",
    trackPreviews: "トラックプレビュー",
    totalListens: "総再生数",
    totalSales: "総売上",
    grossRevenue: "総収益",
    yourPayout: "あなたの支払い",
    tracks: "マイトラック",
    editTrack: "編集",
    deleteTrack: "削除",
    publishTrack: "公開",
    unpublishTrack: "非公開",
    noTracks2: "まだトラックがありません — 最初の曲をアップロード！",
    realTimeStats: "リアルタイム分析",
    royaltiesTitle: "ロイヤリティダッシュボード",
    availableBalance: "利用可能残高",
    requestPayout: "支払いを要求",
    payoutHistory: "支払い履歴",
    bankingInfo: "銀行情報",
    accountHolder: "口座名義人",
    bankName: "銀行名",
    routingNumber: "ルーティング番号",
    accountNumber: "口座番号",
    saveBanking: "銀行情報を保存",
    periodStats: "期間統計",
    unitsSold: "販売数",
    beforeSplit: "分割前",
    payoutRate: "85%アーティスト支払い",
    adminTitle: "管理パネル",
    adminArtists: "アーティスト管理",
    suspend: "停止",
    unsuspend: "停止解除",
    delete: "削除",
    adminLogin: "管理者ログイン",
    adminPinLabel: "管理者PIN",
    manageArtists: "アーティスト管理",
    artistStatus: "ステータス",
    active: "アクティブ",
    suspended: "停止中",
    deleted: "削除済み",
    notifications: "通知",
    noNotifications: "新しい通知はありません",
    artistJoined: "新しいアーティストが参加しました！",
    newComment: "ストアに新しいコメント",
    trackUploaded: "新しいトラックがアップロードされました",
    newSale: "新しい売上！",
    welcomeBack: "おかえりなさい",
    thankYou: "ありがとう！ 👑",
    yourCart: "カート",
    removeItem: "削除",
    proceedToCheckout: "チェックアウトへ",
    downloadNow: "今すぐダウンロード",
    downloadReady: "ダウンロードの準備ができました！",
    purchaseComplete: "購入完了！",
    downloadPrompt: "購入した曲を以下からダウンロードしてください",
    myPurchases: "マイ購入",
    reDownload: "再ダウンロード",
    expires: "有効期限",
    navigation: "ナビゲーション",
    legal: "法律",
    support: "サポート",
    stayInLoop: "🎵 最新情報を受け取る",
    newsletterSubtitle:
      "新しいリリース、ロイヤリティのヒントなど — 直接受信トレイへ。",
    subscribe: "購読",
    termsOfService: "利用規約",
    privacyPolicy: "プライバシーポリシー",
    cookiePolicy: "Cookieポリシー",
    dmca: "DMCA",
    royaltyPolicy: "ロイヤリティポリシー",
    helpCenter: "ヘルプセンター",
    contactUs: "お問い合わせ",
    fileComplaint: "苦情を申し立てる",
    artistResources: "アーティストリソース",
    distributionGuide: "配信ガイド",
    royaltyFaq: "ロイヤリティFAQ",
    language: "言語",
    darkMode: "ダークモード",
    loading: "読み込み中...",
    error: "エラー",
    success: "成功",
    cancel: "キャンセル",
    save: "保存",
    edit: "編集",
    close: "閉じる",
    back: "戻る",
    next: "次へ",
    confirm: "確認",
    yourArtistName: "あなたのアーティスト名",
    support_chat_title: "Chosen One サポート",
    support_chat_welcome:
      "こんにちは！サポートアシスタントです。アップロード、購入、ダウンロード、支払い、アカウント、ロイヤリティについてお気軽にどうぞ。",
    support_chat_placeholder: "質問を入力...",
    support_chat_send: "送信",
    support_chat_thinking: "考え中...",
    support_chat_error:
      "接続に問題があります。もう一度お試しいただくか、ヘルプセンターをご覧ください。",
  },
  ko: {
    home: "홈",
    store: "스토어",
    upload: "업로드",
    dashboard: "아티스트 대시보드",
    royalties: "로열티 대시보드",
    signIn: "로그인",
    signOut: "로그아웃",
    signUp: "가입",
    artistName: "아티스트 이름",
    pinCode: "PIN 코드",
    createAccount: "계정 만들기",
    login: "로그인",
    loginSubtitle: "Chosen One Productions에 오신 것을 환영합니다",
    signupSubtitle: "Chosen One Productions Distribution에 가입하세요",
    enterPin: "PIN 입력",
    confirmPin: "PIN 확인",
    nameLabel: "아티스트 이름",
    pinLabel: "4-6자리 PIN",
    loginBtn: "로그인",
    signupBtn: "계정 만들기",
    noAccount: "계정이 없으신가요?",
    hasAccount: "이미 계정이 있으신가요?",
    storeTitle: "음악 스토어",
    storeSubtitle: "독립 아티스트를 발견하고 지원하세요",
    searchPlaceholder: "노래, 아티스트 검색...",
    allGenres: "모든 장르",
    buyNow: "지금 구매",
    preview: "미리보기",
    addToCart: "장바구니에 추가",
    cart: "장바구니",
    checkout: "결제",
    cartEmpty: "장바구니가 비어 있습니다",
    cartTotal: "합계",
    purchaseNow: "지금 구매",
    liked: "좋아요 됨",
    like: "좋아요",
    share: "공유",
    details: "세부 정보",
    noTracks: "트랙을 찾을 수 없습니다",
    loadingTracks: "트랙 로딩 중...",
    uploadTitle: "음악 업로드",
    uploadSubtitle: "세상과 예술을 공유하세요",
    trackTitle: "트랙 제목",
    genre: "장르",
    price: "가격 (USD)",
    releaseDate: "출시일",
    explicit: "명시적 콘텐츠",
    preOrder: "사전 주문",
    description: "설명",
    songDetails: "노래 세부 정보 (선택사항)",
    coverArt: "커버 아트",
    audioFile: "오디오 파일 (MP3 또는 WAV)",
    uploadBtn: "트랙 업로드",
    uploadingMsg: "업로드 중...",
    previewSelect: "30초 미리보기 선택",
    previewHelp: "파형에서 클릭하고 드래그하여 30초 미리보기 클립을 선택하세요",
    albumUpload: "앨범 업로드",
    singleUpload: "싱글 업로드",
    dashboardTitle: "아티스트 대시보드",
    trackPreviews: "트랙 미리보기",
    totalListens: "총 청취수",
    totalSales: "총 판매량",
    grossRevenue: "총 수익",
    yourPayout: "지급액",
    tracks: "내 트랙",
    editTrack: "편집",
    deleteTrack: "삭제",
    publishTrack: "게시",
    unpublishTrack: "게시 취소",
    noTracks2: "아직 트랙이 없습니다 — 첫 번째 노래를 업로드하세요!",
    realTimeStats: "실시간 분석",
    royaltiesTitle: "로열티 대시보드",
    availableBalance: "사용 가능 잔액",
    requestPayout: "지급 요청",
    payoutHistory: "지급 내역",
    bankingInfo: "은행 정보",
    accountHolder: "계좌 명의인",
    bankName: "은행 이름",
    routingNumber: "라우팅 번호",
    accountNumber: "계좌 번호",
    saveBanking: "은행 정보 저장",
    periodStats: "기간 통계",
    unitsSold: "판매 단위",
    beforeSplit: "분할 전",
    payoutRate: "85% 아티스트 지급",
    adminTitle: "관리자 패널",
    adminArtists: "아티스트 관리",
    suspend: "정지",
    unsuspend: "정지 해제",
    delete: "삭제",
    adminLogin: "관리자 로그인",
    adminPinLabel: "관리자 PIN",
    manageArtists: "아티스트 관리",
    artistStatus: "상태",
    active: "활성",
    suspended: "정지됨",
    deleted: "삭제됨",
    notifications: "알림",
    noNotifications: "새 알림 없음",
    artistJoined: "새 아티스트가 합류했습니다!",
    newComment: "스토어에 새 댓글",
    trackUploaded: "새 트랙 업로드됨",
    newSale: "새 판매!",
    welcomeBack: "다시 오신 것을 환영합니다",
    thankYou: "감사합니다! 👑",
    yourCart: "장바구니",
    removeItem: "제거",
    proceedToCheckout: "결제 진행",
    downloadNow: "지금 다운로드",
    downloadReady: "다운로드 준비 완료!",
    purchaseComplete: "구매 완료!",
    downloadPrompt: "구매한 노래를 아래에서 다운로드하세요",
    myPurchases: "내 구매",
    reDownload: "재다운로드",
    expires: "만료",
    navigation: "탐색",
    legal: "법적",
    support: "지원",
    stayInLoop: "🎵 최신 소식 받기",
    newsletterSubtitle: "새 릴리스, 로열티 팁 등 — 받은 편지함으로 바로.",
    subscribe: "구독",
    termsOfService: "서비스 약관",
    privacyPolicy: "개인정보 처리방침",
    cookiePolicy: "쿠키 정책",
    dmca: "DMCA",
    royaltyPolicy: "로열티 정책",
    helpCenter: "도움말 센터",
    contactUs: "문의하기",
    fileComplaint: "불만 신고",
    artistResources: "아티스트 리소스",
    distributionGuide: "배포 가이드",
    royaltyFaq: "로열티 FAQ",
    language: "언어",
    darkMode: "다크 모드",
    loading: "로딩 중...",
    error: "오류",
    success: "성공",
    cancel: "취소",
    save: "저장",
    edit: "편집",
    close: "닫기",
    back: "뒤로",
    next: "다음",
    confirm: "확인",
    yourArtistName: "아티스트 이름",
    support_chat_title: "Chosen One 지원",
    support_chat_welcome:
      "안녕하세요! 지원 도우미입니다. 업로드, 구매, 다운로드, 결제, 계정, 로열티에 대해 질문하세요.",
    support_chat_placeholder: "질문을 입력하세요...",
    support_chat_send: "전송",
    support_chat_thinking: "생각 중...",
    support_chat_error:
      "연결에 문제가 있습니다. 다시 시도하거나 도움말 센터를 방문해 주세요.",
  },
  ar: {
    home: "الرئيسية",
    store: "المتجر",
    upload: "رفع",
    dashboard: "لوحة تحكم الفنان",
    royalties: "لوحة تحكم الإتاوات",
    signIn: "تسجيل الدخول",
    signOut: "تسجيل الخروج",
    signUp: "إنشاء حساب",
    artistName: "اسم الفنان",
    pinCode: "رمز PIN",
    createAccount: "إنشاء حساب",
    login: "تسجيل الدخول",
    loginSubtitle: "مرحباً بك في Chosen One Productions",
    signupSubtitle: "انضم إلى Chosen One Productions Distribution",
    enterPin: "أدخل رمز PIN",
    confirmPin: "تأكيد رمز PIN",
    nameLabel: "اسم الفنان الخاص بك",
    pinLabel: "رمز PIN من 4-6 أرقام",
    loginBtn: "تسجيل الدخول",
    signupBtn: "إنشاء حساب",
    noAccount: "ليس لديك حساب؟",
    hasAccount: "لديك حساب بالفعل؟",
    storeTitle: "متجر الموسيقى",
    storeSubtitle: "اكتشف وادعم الفنانين المستقلين",
    searchPlaceholder: "البحث عن أغاني، فنانين...",
    allGenres: "جميع الأنواع",
    buyNow: "اشتر الآن",
    preview: "معاينة",
    addToCart: "أضف إلى السلة",
    cart: "السلة",
    checkout: "الدفع",
    cartEmpty: "سلتك فارغة",
    cartTotal: "الإجمالي",
    purchaseNow: "اشتر الآن",
    liked: "معجب",
    like: "إعجاب",
    share: "مشاركة",
    details: "تفاصيل",
    noTracks: "لا توجد مسارات",
    loadingTracks: "جارٍ تحميل المسارات...",
    uploadTitle: "رفع موسيقى",
    uploadSubtitle: "شارك فنك مع العالم",
    trackTitle: "عنوان المسار",
    genre: "النوع",
    price: "السعر (USD)",
    releaseDate: "تاريخ الإصدار",
    explicit: "محتوى صريح",
    preOrder: "طلب مسبق",
    description: "وصف",
    songDetails: "تفاصيل الأغنية (اختياري)",
    coverArt: "غلاف الألبوم",
    audioFile: "ملف صوتي (MP3 أو WAV)",
    uploadBtn: "رفع المسار",
    uploadingMsg: "جارٍ الرفع...",
    previewSelect: "اختر معاينة 30 ثانية",
    previewHelp:
      "انقر واسحب على شكل الموجة لاختيار مقطع المعاينة لمدة 30 ثانية",
    albumUpload: "رفع ألبوم",
    singleUpload: "رفع أغنية فردية",
    dashboardTitle: "لوحة تحكم الفنان",
    trackPreviews: "معاينات المسارات",
    totalListens: "إجمالي الاستماعات",
    totalSales: "إجمالي المبيعات",
    grossRevenue: "الإيرادات الإجمالية",
    yourPayout: "دفعتك",
    tracks: "مساراتي",
    editTrack: "تعديل",
    deleteTrack: "حذف",
    publishTrack: "نشر",
    unpublishTrack: "إلغاء النشر",
    noTracks2: "لا توجد مسارات بعد — ارفع أغنيتك الأولى!",
    realTimeStats: "تحليلات في الوقت الفعلي",
    royaltiesTitle: "لوحة تحكم الإتاوات",
    availableBalance: "الرصيد المتاح",
    requestPayout: "طلب دفعة",
    payoutHistory: "سجل الدفعات",
    bankingInfo: "المعلومات المصرفية",
    accountHolder: "اسم صاحب الحساب",
    bankName: "اسم البنك",
    routingNumber: "رقم التوجيه",
    accountNumber: "رقم الحساب",
    saveBanking: "حفظ المعلومات المصرفية",
    periodStats: "إحصائيات الفترة",
    unitsSold: "الوحدات المباعة",
    beforeSplit: "قبل التقسيم",
    payoutRate: "85% دفعة الفنان",
    adminTitle: "لوحة الإدارة",
    adminArtists: "إدارة الفنانين",
    suspend: "تعليق",
    unsuspend: "إلغاء التعليق",
    delete: "حذف",
    adminLogin: "تسجيل دخول المدير",
    adminPinLabel: "PIN المدير",
    manageArtists: "إدارة الفنانين",
    artistStatus: "الحالة",
    active: "نشط",
    suspended: "معلق",
    deleted: "محذوف",
    notifications: "الإشعارات",
    noNotifications: "لا توجد إشعارات جديدة",
    artistJoined: "انضم فنان جديد!",
    newComment: "تعليق جديد على متجرك",
    trackUploaded: "تم رفع مسار جديد",
    newSale: "بيع جديد!",
    welcomeBack: "مرحباً بعودتك",
    thankYou: "شكراً! 👑",
    yourCart: "سلتك",
    removeItem: "إزالة",
    proceedToCheckout: "المتابعة للدفع",
    downloadNow: "تحميل الآن",
    downloadReady: "تحميلك جاهز!",
    purchaseComplete: "اكتملت عملية الشراء!",
    downloadPrompt: "قم بتحميل أغانيك المشتراة أدناه",
    myPurchases: "مشترياتي",
    reDownload: "إعادة التحميل",
    expires: "تنتهي",
    navigation: "التنقل",
    legal: "قانوني",
    support: "الدعم",
    stayInLoop: "🎵 ابقَ على اطلاع",
    newsletterSubtitle:
      "إصدارات جديدة، نصائح الإتاوات والمزيد — مباشرة إلى بريدك الوارد.",
    subscribe: "اشترك",
    termsOfService: "شروط الخدمة",
    privacyPolicy: "سياسة الخصوصية",
    cookiePolicy: "سياسة ملفات تعريف الارتباط",
    dmca: "DMCA",
    royaltyPolicy: "سياسة الإتاوات",
    helpCenter: "مركز المساعدة",
    contactUs: "تواصل معنا",
    fileComplaint: "تقديم شكوى",
    artistResources: "موارد الفنانين",
    distributionGuide: "دليل التوزيع",
    royaltyFaq: "أسئلة شائعة عن الإتاوات",
    language: "اللغة",
    darkMode: "الوضع الداكن",
    loading: "جارٍ التحميل...",
    error: "خطأ",
    success: "نجاح",
    cancel: "إلغاء",
    save: "حفظ",
    edit: "تعديل",
    close: "إغلاق",
    back: "رجوع",
    next: "التالي",
    confirm: "تأكيد",
    yourArtistName: "اسم الفنان الخاص بك",
    support_chat_title: "دعم Chosen One",
    support_chat_welcome:
      "مرحباً! أنا مساعد الدعم الخاص بك. اسألني عن الرفع، الشراء، التحميل، المدفوعات، الحسابات، أو الإتاوات.",
    support_chat_placeholder: "اكتب سؤالك...",
    support_chat_send: "إرسال",
    support_chat_thinking: "جارٍ التفكير...",
    support_chat_error:
      "أواجه مشكلة في الاتصال. يرجى المحاولة مرة أخرى أو زيارة مركز المساعدة.",
  },
};

export type {
  ArtistProfilePublic,
  ArtistDashboardStats,
  ArtistTrackSummary,
  TrackMetadataPublic,
  TrackUploadInput,
  RoyaltyDashboard,
  TrackRoyalty,
  PayoutPublic,
  BankingInfoPublic,
  StoreCommentPublic,
  ShoppingItem,
  StripeConfiguration,
  StripeSessionStatus,
  PeriodStats,
  Notification,
  RealTimeDashboardStats,
  DownloadReportEntry,
  ArtistAdminView,
  AdminTrafficStats,
} from "../backend";

export {
  PayoutStatus,
  TrackState,
  TrackType,
  UserRole,
  ArtistStatus,
  LikeResult,
  NotificationType,
} from "../backend";
