/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminTrafficStats {
  'activeVisitors' : bigint,
  'totalPreviewsAllTime' : bigint,
  'recentSignups' : bigint,
  'grossRevenueCents' : bigint,
  'pageViewsBySection' : Array<[string, bigint]>,
  'pageViewsLast5Min' : bigint,
  'totalSalesAllTime' : bigint,
  'totalPublishedTracks' : bigint,
  'recentPurchases' : bigint,
}
export interface ArtistAdminView {
  'id' : ArtistId,
  'bio' : string,
  'status' : ArtistStatus,
  'lastLoginAt' : [] | [Timestamp],
  'name' : string,
  'createdAt' : Timestamp,
}
export interface ArtistDashboardStats {
  'totalTracks' : bigint,
  'totalEarningsCents' : bigint,
  'totalPreviews' : bigint,
  'totalSales' : bigint,
}
export type ArtistId = string;
export interface ArtistProfilePublic {
  'id' : ArtistId,
  'bio' : string,
  'status' : ArtistStatus,
  'tiktok' : [] | [string],
  'soundcloud' : [] | [string],
  'instagram' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'twitterX' : [] | [string],
  'website' : [] | [string],
  'facebook' : [] | [string],
  'spotify' : [] | [string],
  'youtube' : [] | [string],
  'appleMusic' : [] | [string],
}
export interface ArtistSocialLinks {
  'tiktok' : [] | [string],
  'soundcloud' : [] | [string],
  'instagram' : [] | [string],
  'twitterX' : [] | [string],
  'website' : [] | [string],
  'facebook' : [] | [string],
  'spotify' : [] | [string],
  'youtube' : [] | [string],
  'appleMusic' : [] | [string],
}
export type ArtistStatus = { 'deleted' : null } |
  { 'active' : null } |
  { 'suspended' : null };
export interface ArtistTrackSummary {
  'id' : TrackId,
  'title' : string,
  'trackType' : TrackType,
  'saleCount' : bigint,
  'state' : TrackState,
  'previewCount' : bigint,
  'genre' : string,
  'priceInCents' : bigint,
  'releaseDate' : string,
}
export interface BankingInfoPublic {
  'routingNumber' : string,
  'artistId' : ArtistId,
  'accountHolderName' : string,
  'bankName' : string,
  'updatedAt' : Timestamp,
  'accountNumber' : string,
}
export type CommentId = bigint;
export interface DownloadReportEntry {
  'expiresAt' : Timestamp,
  'saleId' : SaleId,
  'trackTitle' : string,
  'downloadAvailable' : boolean,
  'purchasedAt' : Timestamp,
  'trackId' : TrackId,
  'artistName' : string,
  'format' : string,
}
export type ExternalBlob = Uint8Array;
export type LikeResult = { 'ok' : null } |
  { 'notLiked' : null } |
  { 'alreadyLiked' : null };
export interface Notification {
  'id' : bigint,
  'notifType' : NotificationType,
  'artistId' : ArtistId,
  'message' : string,
  'recipientToken' : [] | [string],
  'timestamp' : Timestamp,
}
export type NotificationType = { 'artistJoined' : null } |
  { 'newComment' : null } |
  { 'trackUploaded' : null } |
  { 'newDrop' : null } |
  { 'newSale' : null };
export type PayoutId = bigint;
export interface PayoutPublic {
  'id' : PayoutId,
  'status' : PayoutStatus,
  'artistId' : ArtistId,
  'amountCents' : bigint,
  'processedAt' : [] | [Timestamp],
  'requestedAt' : Timestamp,
}
export type PayoutStatus = { 'pending' : null } |
  { 'processed' : null } |
  { 'failed' : null };
export interface PeriodStats {
  'previews' : bigint,
  'grossRevenueCents' : bigint,
  'sales' : bigint,
  'periodLabel' : string,
  'payoutCents' : bigint,
}
export interface RealTimeDashboardStats {
  'trackPreviews' : bigint,
  'totalSales' : bigint,
  'grossRevenue' : bigint,
  'artistPayout' : bigint,
  'totalListens' : bigint,
}
export interface RoyaltyDashboard {
  'trackBreakdown' : Array<TrackRoyalty>,
  'availableBalanceCents' : bigint,
  'periodStats' : PeriodStats,
  'payouts' : Array<PayoutPublic>,
}
export type SaleId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StoreCommentPublic {
  'id' : CommentId,
  'authorId' : ArtistId,
  'body' : string,
  'createdAt' : Timestamp,
  'authorName' : string,
  'rating' : bigint,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Timestamp = bigint;
export type TrackId = bigint;
export interface TrackMetadataPublic {
  'id' : TrackId,
  'title' : string,
  'likeCount' : bigint,
  'trackType' : TrackType,
  'saleCount' : bigint,
  'previewEndSecs' : number,
  'createdAt' : Timestamp,
  'previewStartSecs' : number,
  'explicit' : boolean,
  'artistId' : ArtistId,
  'description' : string,
  'audioFile' : ExternalBlob,
  'songDetails' : string,
  'state' : TrackState,
  'previewCount' : bigint,
  'genre' : string,
  'preOrder' : boolean,
  'artistName' : string,
  'coverArt' : ExternalBlob,
  'priceInCents' : bigint,
  'releaseDate' : string,
}
export interface TrackRoyalty {
  'title' : string,
  'earningsCents' : bigint,
  'previews' : bigint,
  'grossRevenueCents' : bigint,
  'sales' : bigint,
  'trackId' : TrackId,
}
export type TrackState = { 'deleted' : null } |
  { 'published' : null } |
  { 'uploaded' : null } |
  { 'preOrder' : null };
export type TrackType = { 'album' : null } |
  { 'single' : null };
export interface TrackUploadInput {
  'title' : string,
  'trackType' : TrackType,
  'previewEndSecs' : [] | [number],
  'previewStartSecs' : [] | [number],
  'explicit' : boolean,
  'description' : string,
  'audioFile' : ExternalBlob,
  'songDetails' : [] | [string],
  'genre' : string,
  'preOrder' : boolean,
  'artistName' : string,
  'coverArt' : ExternalBlob,
  'priceInCents' : bigint,
  'releaseDate' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addStoreComment' : ActorMethod<
    [string, string, string, bigint],
    { 'ok' : CommentId } |
      { 'err' : string }
  >,
  'adminChangePIN' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminDeleteArtist' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminInitializePIN' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminListArtists' : ActorMethod<
    [string],
    { 'ok' : Array<ArtistAdminView> } |
      { 'err' : string }
  >,
  'adminLogin' : ActorMethod<[string], { 'ok' : string } | { 'err' : string }>,
  'adminLogout' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'adminResetArtistPIN' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminSuspendArtist' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'adminUnsuspendArtist' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'askSupportChat' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'changePIN' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createTrackCheckoutSession' : ActorMethod<
    [string, TrackId, string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'deleteArtistAccount' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteTrack' : ActorMethod<
    [string, TrackId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'filterTracksByGenre' : ActorMethod<[string], Array<TrackMetadataPublic>>,
  'fulfillTrackPurchase' : ActorMethod<
    [string, TrackId, string, [] | [string]],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAdminTrafficStats' : ActorMethod<
    [string],
    { 'ok' : AdminTrafficStats } |
      { 'err' : string }
  >,
  'getArtistDashboardStats' : ActorMethod<
    [string],
    { 'ok' : ArtistDashboardStats } |
      { 'err' : string }
  >,
  'getArtistProfile' : ActorMethod<
    [ArtistId],
    { 'ok' : ArtistProfilePublic } |
      { 'err' : string }
  >,
  'getArtistSecurityQuestion' : ActorMethod<[string], [] | [string]>,
  'getArtistStoreLikes' : ActorMethod<[string], bigint>,
  'getArtistTracks' : ActorMethod<
    [string],
    { 'ok' : Array<ArtistTrackSummary> } |
      { 'err' : string }
  >,
  'getBankingInfo' : ActorMethod<
    [string],
    { 'ok' : [] | [BankingInfoPublic] } |
      { 'err' : string }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerDownloadReport' : ActorMethod<
    [string],
    { 'ok' : Array<DownloadReportEntry> } |
      { 'err' : string }
  >,
  'getCustomerPurchases' : ActorMethod<
    [string],
    { 'ok' : Array<TrackMetadataPublic> } |
      { 'err' : string }
  >,
  'getDownloadReport' : ActorMethod<
    [string],
    { 'ok' : Array<DownloadReportEntry> } |
      { 'err' : string }
  >,
  'getMailingListSubscribers' : ActorMethod<[], Array<string>>,
  'getMyArtistProfile' : ActorMethod<[string], [] | [ArtistProfilePublic]>,
  'getMyPayouts' : ActorMethod<
    [string],
    { 'ok' : Array<PayoutPublic> } |
      { 'err' : string }
  >,
  'getPurchasedTracks' : ActorMethod<
    [string],
    { 'ok' : Array<TrackMetadataPublic> } |
      { 'err' : string }
  >,
  'getRealTimeDashboardStats' : ActorMethod<
    [string],
    { 'ok' : RealTimeDashboardStats } |
      { 'err' : string }
  >,
  'getRecentNotifications' : ActorMethod<[string], Array<Notification>>,
  'getRoyaltyDashboard' : ActorMethod<
    [string, string],
    { 'ok' : RoyaltyDashboard } |
      { 'err' : string }
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getStripeSessionStatus_internal' : ActorMethod<
    [string],
    StripeSessionStatus
  >,
  'getTrack' : ActorMethod<[TrackId], [] | [TrackMetadataPublic]>,
  'getTrackLikes' : ActorMethod<[bigint], bigint>,
  'getTracksByArtist' : ActorMethod<[ArtistId], Array<TrackMetadataPublic>>,
  'hasLikedStore' : ActorMethod<[string, string], boolean>,
  'hasLikedTrack' : ActorMethod<[bigint, string], boolean>,
  'incrementPreviewCount' : ActorMethod<[TrackId], undefined>,
  'isAdminSession' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'likeArtistStore' : ActorMethod<[string, string], LikeResult>,
  'likeTrack' : ActorMethod<[bigint, string], LikeResult>,
  'listPublishedTracks' : ActorMethod<[], Array<TrackMetadataPublic>>,
  'listStoreComments' : ActorMethod<[], Array<StoreCommentPublic>>,
  'loginArtist' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'loginCustomer' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'logoutArtist' : ActorMethod<[string], { 'ok' : null } | { 'err' : string }>,
  'logoutCustomer' : ActorMethod<[string], undefined>,
  'notifyArtistJoined' : ActorMethod<[string], undefined>,
  'notifyNewComment' : ActorMethod<[ArtistId, string], undefined>,
  'notifyNewSale' : ActorMethod<[ArtistId, string], undefined>,
  'notifyTrackUploaded' : ActorMethod<[string, string], undefined>,
  'publishTrack' : ActorMethod<
    [string, TrackId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'recordPageView' : ActorMethod<[string, string], undefined>,
  'requestPayout' : ActorMethod<
    [string, bigint],
    { 'ok' : PayoutId } |
      { 'err' : string }
  >,
  'resetPINWithSecurityAnswer' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'saveBankingInfo' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'searchTracks' : ActorMethod<[string], Array<TrackMetadataPublic>>,
  'setArtistSecurityQuestion' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'setStripeConfiguration' : ActorMethod<
    [string, StripeConfiguration],
    undefined
  >,
  'signupArtist' : ActorMethod<
    [string, string],
    { 'ok' : ArtistProfilePublic } |
      { 'err' : string }
  >,
  'signupCustomer' : ActorMethod<
    [string, string],
    { 'ok' : string } |
      { 'err' : string }
  >,
  'subscribeToMailingList' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unlikeArtistStore' : ActorMethod<[string, string], LikeResult>,
  'unlikeTrack' : ActorMethod<[bigint, string], LikeResult>,
  'unpublishTrack' : ActorMethod<
    [string, TrackId],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateArtistProfile' : ActorMethod<
    [string, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateArtistSocialLinks' : ActorMethod<
    [string, ArtistSocialLinks],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateTrackMetadata' : ActorMethod<
    [
      string,
      TrackId,
      string,
      string,
      bigint,
      string,
      string,
      boolean,
      boolean,
      [] | [number],
      [] | [number],
      [] | [string],
    ],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'uploadTrack' : ActorMethod<
    [string, TrackUploadInput],
    { 'ok' : TrackId } |
      { 'err' : string }
  >,
  'validateCustomerSession' : ActorMethod<[string], boolean>,
  'validateSession' : ActorMethod<
    [string],
    { 'ok' : ArtistId } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];