/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CommentId = IDL.Nat;
export const ArtistId = IDL.Text;
export const ArtistStatus = IDL.Variant({
  'deleted' : IDL.Null,
  'active' : IDL.Null,
  'suspended' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const ArtistAdminView = IDL.Record({
  'id' : ArtistId,
  'bio' : IDL.Text,
  'status' : ArtistStatus,
  'lastLoginAt' : IDL.Opt(Timestamp),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const TrackId = IDL.Nat;
export const TrackType = IDL.Variant({
  'album' : IDL.Null,
  'single' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const TrackState = IDL.Variant({
  'deleted' : IDL.Null,
  'published' : IDL.Null,
  'uploaded' : IDL.Null,
  'preOrder' : IDL.Null,
});
export const TrackMetadataPublic = IDL.Record({
  'id' : TrackId,
  'title' : IDL.Text,
  'likeCount' : IDL.Nat,
  'trackType' : TrackType,
  'saleCount' : IDL.Nat,
  'previewEndSecs' : IDL.Float64,
  'createdAt' : Timestamp,
  'previewStartSecs' : IDL.Float64,
  'explicit' : IDL.Bool,
  'artistId' : ArtistId,
  'description' : IDL.Text,
  'audioFile' : ExternalBlob,
  'songDetails' : IDL.Text,
  'state' : TrackState,
  'previewCount' : IDL.Nat,
  'genre' : IDL.Text,
  'preOrder' : IDL.Bool,
  'artistName' : IDL.Text,
  'coverArt' : ExternalBlob,
  'priceInCents' : IDL.Nat,
  'releaseDate' : IDL.Text,
});
export const ArtistDashboardStats = IDL.Record({
  'totalTracks' : IDL.Nat,
  'totalEarningsCents' : IDL.Nat,
  'totalPreviews' : IDL.Nat,
  'totalSales' : IDL.Nat,
});
export const ArtistProfilePublic = IDL.Record({
  'id' : ArtistId,
  'bio' : IDL.Text,
  'status' : ArtistStatus,
  'tiktok' : IDL.Opt(IDL.Text),
  'soundcloud' : IDL.Opt(IDL.Text),
  'instagram' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'twitterX' : IDL.Opt(IDL.Text),
  'website' : IDL.Opt(IDL.Text),
  'facebook' : IDL.Opt(IDL.Text),
  'spotify' : IDL.Opt(IDL.Text),
  'youtube' : IDL.Opt(IDL.Text),
  'appleMusic' : IDL.Opt(IDL.Text),
});
export const ArtistTrackSummary = IDL.Record({
  'id' : TrackId,
  'title' : IDL.Text,
  'trackType' : TrackType,
  'saleCount' : IDL.Nat,
  'state' : TrackState,
  'previewCount' : IDL.Nat,
  'genre' : IDL.Text,
  'priceInCents' : IDL.Nat,
  'releaseDate' : IDL.Text,
});
export const BankingInfoPublic = IDL.Record({
  'routingNumber' : IDL.Text,
  'artistId' : ArtistId,
  'accountHolderName' : IDL.Text,
  'bankName' : IDL.Text,
  'updatedAt' : Timestamp,
  'accountNumber' : IDL.Text,
});
export const SaleId = IDL.Nat;
export const DownloadReportEntry = IDL.Record({
  'expiresAt' : Timestamp,
  'saleId' : SaleId,
  'trackTitle' : IDL.Text,
  'downloadAvailable' : IDL.Bool,
  'purchasedAt' : Timestamp,
  'trackId' : TrackId,
  'artistName' : IDL.Text,
  'format' : IDL.Text,
});
export const PayoutId = IDL.Nat;
export const PayoutStatus = IDL.Variant({
  'pending' : IDL.Null,
  'processed' : IDL.Null,
  'failed' : IDL.Null,
});
export const PayoutPublic = IDL.Record({
  'id' : PayoutId,
  'status' : PayoutStatus,
  'artistId' : ArtistId,
  'amountCents' : IDL.Nat,
  'processedAt' : IDL.Opt(Timestamp),
  'requestedAt' : Timestamp,
});
export const RealTimeDashboardStats = IDL.Record({
  'trackPreviews' : IDL.Nat,
  'totalSales' : IDL.Nat,
  'grossRevenue' : IDL.Nat,
  'artistPayout' : IDL.Nat,
  'totalListens' : IDL.Nat,
});
export const NotificationType = IDL.Variant({
  'artistJoined' : IDL.Null,
  'newComment' : IDL.Null,
  'trackUploaded' : IDL.Null,
  'newDrop' : IDL.Null,
  'newSale' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'notifType' : NotificationType,
  'artistId' : ArtistId,
  'message' : IDL.Text,
  'recipientToken' : IDL.Opt(IDL.Text),
  'timestamp' : Timestamp,
});
export const TrackRoyalty = IDL.Record({
  'title' : IDL.Text,
  'earningsCents' : IDL.Nat,
  'previews' : IDL.Nat,
  'grossRevenueCents' : IDL.Nat,
  'sales' : IDL.Nat,
  'trackId' : TrackId,
});
export const PeriodStats = IDL.Record({
  'previews' : IDL.Nat,
  'grossRevenueCents' : IDL.Nat,
  'sales' : IDL.Nat,
  'periodLabel' : IDL.Text,
  'payoutCents' : IDL.Nat,
});
export const RoyaltyDashboard = IDL.Record({
  'trackBreakdown' : IDL.Vec(TrackRoyalty),
  'availableBalanceCents' : IDL.Nat,
  'periodStats' : PeriodStats,
  'payouts' : IDL.Vec(PayoutPublic),
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const LikeResult = IDL.Variant({
  'ok' : IDL.Null,
  'notLiked' : IDL.Null,
  'alreadyLiked' : IDL.Null,
});
export const StoreCommentPublic = IDL.Record({
  'id' : CommentId,
  'authorId' : ArtistId,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'authorName' : IDL.Text,
  'rating' : IDL.Nat,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const ArtistSocialLinks = IDL.Record({
  'tiktok' : IDL.Opt(IDL.Text),
  'soundcloud' : IDL.Opt(IDL.Text),
  'instagram' : IDL.Opt(IDL.Text),
  'twitterX' : IDL.Opt(IDL.Text),
  'website' : IDL.Opt(IDL.Text),
  'facebook' : IDL.Opt(IDL.Text),
  'spotify' : IDL.Opt(IDL.Text),
  'youtube' : IDL.Opt(IDL.Text),
  'appleMusic' : IDL.Opt(IDL.Text),
});
export const TrackUploadInput = IDL.Record({
  'title' : IDL.Text,
  'trackType' : TrackType,
  'previewEndSecs' : IDL.Opt(IDL.Float64),
  'previewStartSecs' : IDL.Opt(IDL.Float64),
  'explicit' : IDL.Bool,
  'description' : IDL.Text,
  'audioFile' : ExternalBlob,
  'songDetails' : IDL.Opt(IDL.Text),
  'genre' : IDL.Text,
  'preOrder' : IDL.Bool,
  'artistName' : IDL.Text,
  'coverArt' : ExternalBlob,
  'priceInCents' : IDL.Nat,
  'releaseDate' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addStoreComment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : CommentId, 'err' : IDL.Text })],
      [],
    ),
  'adminChangePIN' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminDeleteArtist' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminInitializePIN' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminListArtists' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(ArtistAdminView), 'err' : IDL.Text })],
      ['query'],
    ),
  'adminLogin' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'adminLogout' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminResetArtistPIN' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminSuspendArtist' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'adminUnsuspendArtist' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'askSupportChat' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'changePIN' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createTrackCheckoutSession' : IDL.Func(
      [IDL.Text, TrackId, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'deleteArtistAccount' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteTrack' : IDL.Func(
      [IDL.Text, TrackId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'filterTracksByGenre' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TrackMetadataPublic)],
      ['query'],
    ),
  'fulfillTrackPurchase' : IDL.Func(
      [IDL.Text, TrackId, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getArtistDashboardStats' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : ArtistDashboardStats, 'err' : IDL.Text })],
      ['query'],
    ),
  'getArtistProfile' : IDL.Func(
      [ArtistId],
      [IDL.Variant({ 'ok' : ArtistProfilePublic, 'err' : IDL.Text })],
      ['query'],
    ),
  'getArtistSecurityQuestion' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'getArtistStoreLikes' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getArtistTracks' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(ArtistTrackSummary), 'err' : IDL.Text })],
      ['query'],
    ),
  'getBankingInfo' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Opt(BankingInfoPublic), 'err' : IDL.Text })],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerDownloadReport' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(DownloadReportEntry), 'err' : IDL.Text })],
      ['query'],
    ),
  'getCustomerPurchases' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(TrackMetadataPublic), 'err' : IDL.Text })],
      ['query'],
    ),
  'getDownloadReport' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(DownloadReportEntry), 'err' : IDL.Text })],
      ['query'],
    ),
  'getMailingListSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getMyArtistProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ArtistProfilePublic)],
      ['query'],
    ),
  'getMyPayouts' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(PayoutPublic), 'err' : IDL.Text })],
      ['query'],
    ),
  'getPurchasedTracks' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(TrackMetadataPublic), 'err' : IDL.Text })],
      ['query'],
    ),
  'getRealTimeDashboardStats' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : RealTimeDashboardStats, 'err' : IDL.Text })],
      ['query'],
    ),
  'getRecentNotifications' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Notification)],
      ['query'],
    ),
  'getRoyaltyDashboard' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : RoyaltyDashboard, 'err' : IDL.Text })],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getStripeSessionStatus_internal' : IDL.Func(
      [IDL.Text],
      [StripeSessionStatus],
      [],
    ),
  'getTrack' : IDL.Func([TrackId], [IDL.Opt(TrackMetadataPublic)], ['query']),
  'getTrackLikes' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getTracksByArtist' : IDL.Func(
      [ArtistId],
      [IDL.Vec(TrackMetadataPublic)],
      ['query'],
    ),
  'hasLikedStore' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'hasLikedTrack' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], ['query']),
  'incrementPreviewCount' : IDL.Func([TrackId], [], []),
  'isAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'likeArtistStore' : IDL.Func([IDL.Text, IDL.Text], [LikeResult], []),
  'likeTrack' : IDL.Func([IDL.Nat, IDL.Text], [LikeResult], []),
  'listPublishedTracks' : IDL.Func(
      [],
      [IDL.Vec(TrackMetadataPublic)],
      ['query'],
    ),
  'listStoreComments' : IDL.Func([], [IDL.Vec(StoreCommentPublic)], ['query']),
  'loginArtist' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'loginCustomer' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'logoutArtist' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'logoutCustomer' : IDL.Func([IDL.Text], [], []),
  'notifyArtistJoined' : IDL.Func([IDL.Text], [], []),
  'notifyNewComment' : IDL.Func([ArtistId, IDL.Text], [], []),
  'notifyNewSale' : IDL.Func([ArtistId, IDL.Text], [], []),
  'notifyTrackUploaded' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'publishTrack' : IDL.Func(
      [IDL.Text, TrackId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'requestPayout' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : PayoutId, 'err' : IDL.Text })],
      [],
    ),
  'resetPINWithSecurityAnswer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'saveBankingInfo' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'searchTracks' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TrackMetadataPublic)],
      ['query'],
    ),
  'setArtistSecurityQuestion' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'setStripeConfiguration' : IDL.Func([IDL.Text, StripeConfiguration], [], []),
  'signupArtist' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : ArtistProfilePublic, 'err' : IDL.Text })],
      [],
    ),
  'signupCustomer' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
      [],
    ),
  'subscribeToMailingList' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unlikeArtistStore' : IDL.Func([IDL.Text, IDL.Text], [LikeResult], []),
  'unlikeTrack' : IDL.Func([IDL.Nat, IDL.Text], [LikeResult], []),
  'unpublishTrack' : IDL.Func(
      [IDL.Text, TrackId],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateArtistProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateArtistSocialLinks' : IDL.Func(
      [IDL.Text, ArtistSocialLinks],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'updateTrackMetadata' : IDL.Func(
      [
        IDL.Text,
        TrackId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'uploadTrack' : IDL.Func(
      [IDL.Text, TrackUploadInput],
      [IDL.Variant({ 'ok' : TrackId, 'err' : IDL.Text })],
      [],
    ),
  'validateCustomerSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'validateSession' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : ArtistId, 'err' : IDL.Text })],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CommentId = IDL.Nat;
  const ArtistId = IDL.Text;
  const ArtistStatus = IDL.Variant({
    'deleted' : IDL.Null,
    'active' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const ArtistAdminView = IDL.Record({
    'id' : ArtistId,
    'bio' : IDL.Text,
    'status' : ArtistStatus,
    'lastLoginAt' : IDL.Opt(Timestamp),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const TrackId = IDL.Nat;
  const TrackType = IDL.Variant({ 'album' : IDL.Null, 'single' : IDL.Null });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const TrackState = IDL.Variant({
    'deleted' : IDL.Null,
    'published' : IDL.Null,
    'uploaded' : IDL.Null,
    'preOrder' : IDL.Null,
  });
  const TrackMetadataPublic = IDL.Record({
    'id' : TrackId,
    'title' : IDL.Text,
    'likeCount' : IDL.Nat,
    'trackType' : TrackType,
    'saleCount' : IDL.Nat,
    'previewEndSecs' : IDL.Float64,
    'createdAt' : Timestamp,
    'previewStartSecs' : IDL.Float64,
    'explicit' : IDL.Bool,
    'artistId' : ArtistId,
    'description' : IDL.Text,
    'audioFile' : ExternalBlob,
    'songDetails' : IDL.Text,
    'state' : TrackState,
    'previewCount' : IDL.Nat,
    'genre' : IDL.Text,
    'preOrder' : IDL.Bool,
    'artistName' : IDL.Text,
    'coverArt' : ExternalBlob,
    'priceInCents' : IDL.Nat,
    'releaseDate' : IDL.Text,
  });
  const ArtistDashboardStats = IDL.Record({
    'totalTracks' : IDL.Nat,
    'totalEarningsCents' : IDL.Nat,
    'totalPreviews' : IDL.Nat,
    'totalSales' : IDL.Nat,
  });
  const ArtistProfilePublic = IDL.Record({
    'id' : ArtistId,
    'bio' : IDL.Text,
    'status' : ArtistStatus,
    'tiktok' : IDL.Opt(IDL.Text),
    'soundcloud' : IDL.Opt(IDL.Text),
    'instagram' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'twitterX' : IDL.Opt(IDL.Text),
    'website' : IDL.Opt(IDL.Text),
    'facebook' : IDL.Opt(IDL.Text),
    'spotify' : IDL.Opt(IDL.Text),
    'youtube' : IDL.Opt(IDL.Text),
    'appleMusic' : IDL.Opt(IDL.Text),
  });
  const ArtistTrackSummary = IDL.Record({
    'id' : TrackId,
    'title' : IDL.Text,
    'trackType' : TrackType,
    'saleCount' : IDL.Nat,
    'state' : TrackState,
    'previewCount' : IDL.Nat,
    'genre' : IDL.Text,
    'priceInCents' : IDL.Nat,
    'releaseDate' : IDL.Text,
  });
  const BankingInfoPublic = IDL.Record({
    'routingNumber' : IDL.Text,
    'artistId' : ArtistId,
    'accountHolderName' : IDL.Text,
    'bankName' : IDL.Text,
    'updatedAt' : Timestamp,
    'accountNumber' : IDL.Text,
  });
  const SaleId = IDL.Nat;
  const DownloadReportEntry = IDL.Record({
    'expiresAt' : Timestamp,
    'saleId' : SaleId,
    'trackTitle' : IDL.Text,
    'downloadAvailable' : IDL.Bool,
    'purchasedAt' : Timestamp,
    'trackId' : TrackId,
    'artistName' : IDL.Text,
    'format' : IDL.Text,
  });
  const PayoutId = IDL.Nat;
  const PayoutStatus = IDL.Variant({
    'pending' : IDL.Null,
    'processed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PayoutPublic = IDL.Record({
    'id' : PayoutId,
    'status' : PayoutStatus,
    'artistId' : ArtistId,
    'amountCents' : IDL.Nat,
    'processedAt' : IDL.Opt(Timestamp),
    'requestedAt' : Timestamp,
  });
  const RealTimeDashboardStats = IDL.Record({
    'trackPreviews' : IDL.Nat,
    'totalSales' : IDL.Nat,
    'grossRevenue' : IDL.Nat,
    'artistPayout' : IDL.Nat,
    'totalListens' : IDL.Nat,
  });
  const NotificationType = IDL.Variant({
    'artistJoined' : IDL.Null,
    'newComment' : IDL.Null,
    'trackUploaded' : IDL.Null,
    'newDrop' : IDL.Null,
    'newSale' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'notifType' : NotificationType,
    'artistId' : ArtistId,
    'message' : IDL.Text,
    'recipientToken' : IDL.Opt(IDL.Text),
    'timestamp' : Timestamp,
  });
  const TrackRoyalty = IDL.Record({
    'title' : IDL.Text,
    'earningsCents' : IDL.Nat,
    'previews' : IDL.Nat,
    'grossRevenueCents' : IDL.Nat,
    'sales' : IDL.Nat,
    'trackId' : TrackId,
  });
  const PeriodStats = IDL.Record({
    'previews' : IDL.Nat,
    'grossRevenueCents' : IDL.Nat,
    'sales' : IDL.Nat,
    'periodLabel' : IDL.Text,
    'payoutCents' : IDL.Nat,
  });
  const RoyaltyDashboard = IDL.Record({
    'trackBreakdown' : IDL.Vec(TrackRoyalty),
    'availableBalanceCents' : IDL.Nat,
    'periodStats' : PeriodStats,
    'payouts' : IDL.Vec(PayoutPublic),
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const LikeResult = IDL.Variant({
    'ok' : IDL.Null,
    'notLiked' : IDL.Null,
    'alreadyLiked' : IDL.Null,
  });
  const StoreCommentPublic = IDL.Record({
    'id' : CommentId,
    'authorId' : ArtistId,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'authorName' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const ArtistSocialLinks = IDL.Record({
    'tiktok' : IDL.Opt(IDL.Text),
    'soundcloud' : IDL.Opt(IDL.Text),
    'instagram' : IDL.Opt(IDL.Text),
    'twitterX' : IDL.Opt(IDL.Text),
    'website' : IDL.Opt(IDL.Text),
    'facebook' : IDL.Opt(IDL.Text),
    'spotify' : IDL.Opt(IDL.Text),
    'youtube' : IDL.Opt(IDL.Text),
    'appleMusic' : IDL.Opt(IDL.Text),
  });
  const TrackUploadInput = IDL.Record({
    'title' : IDL.Text,
    'trackType' : TrackType,
    'previewEndSecs' : IDL.Opt(IDL.Float64),
    'previewStartSecs' : IDL.Opt(IDL.Float64),
    'explicit' : IDL.Bool,
    'description' : IDL.Text,
    'audioFile' : ExternalBlob,
    'songDetails' : IDL.Opt(IDL.Text),
    'genre' : IDL.Text,
    'preOrder' : IDL.Bool,
    'artistName' : IDL.Text,
    'coverArt' : ExternalBlob,
    'priceInCents' : IDL.Nat,
    'releaseDate' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addStoreComment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : CommentId, 'err' : IDL.Text })],
        [],
      ),
    'adminChangePIN' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminDeleteArtist' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminInitializePIN' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminListArtists' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(ArtistAdminView), 'err' : IDL.Text })],
        ['query'],
      ),
    'adminLogin' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'adminLogout' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminResetArtistPIN' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminSuspendArtist' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'adminUnsuspendArtist' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'askSupportChat' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'changePIN' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createTrackCheckoutSession' : IDL.Func(
        [IDL.Text, TrackId, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'deleteArtistAccount' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteTrack' : IDL.Func(
        [IDL.Text, TrackId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'filterTracksByGenre' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TrackMetadataPublic)],
        ['query'],
      ),
    'fulfillTrackPurchase' : IDL.Func(
        [IDL.Text, TrackId, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getArtistDashboardStats' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : ArtistDashboardStats, 'err' : IDL.Text })],
        ['query'],
      ),
    'getArtistProfile' : IDL.Func(
        [ArtistId],
        [IDL.Variant({ 'ok' : ArtistProfilePublic, 'err' : IDL.Text })],
        ['query'],
      ),
    'getArtistSecurityQuestion' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'getArtistStoreLikes' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getArtistTracks' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(ArtistTrackSummary), 'err' : IDL.Text })],
        ['query'],
      ),
    'getBankingInfo' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Opt(BankingInfoPublic), 'err' : IDL.Text })],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerDownloadReport' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Vec(DownloadReportEntry),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getCustomerPurchases' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Vec(TrackMetadataPublic),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getDownloadReport' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Vec(DownloadReportEntry),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getMailingListSubscribers' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getMyArtistProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ArtistProfilePublic)],
        ['query'],
      ),
    'getMyPayouts' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(PayoutPublic), 'err' : IDL.Text })],
        ['query'],
      ),
    'getPurchasedTracks' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Vec(TrackMetadataPublic),
            'err' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getRealTimeDashboardStats' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : RealTimeDashboardStats, 'err' : IDL.Text })],
        ['query'],
      ),
    'getRecentNotifications' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Notification)],
        ['query'],
      ),
    'getRoyaltyDashboard' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : RoyaltyDashboard, 'err' : IDL.Text })],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getStripeSessionStatus_internal' : IDL.Func(
        [IDL.Text],
        [StripeSessionStatus],
        [],
      ),
    'getTrack' : IDL.Func([TrackId], [IDL.Opt(TrackMetadataPublic)], ['query']),
    'getTrackLikes' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getTracksByArtist' : IDL.Func(
        [ArtistId],
        [IDL.Vec(TrackMetadataPublic)],
        ['query'],
      ),
    'hasLikedStore' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'hasLikedTrack' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Bool], ['query']),
    'incrementPreviewCount' : IDL.Func([TrackId], [], []),
    'isAdminSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'likeArtistStore' : IDL.Func([IDL.Text, IDL.Text], [LikeResult], []),
    'likeTrack' : IDL.Func([IDL.Nat, IDL.Text], [LikeResult], []),
    'listPublishedTracks' : IDL.Func(
        [],
        [IDL.Vec(TrackMetadataPublic)],
        ['query'],
      ),
    'listStoreComments' : IDL.Func(
        [],
        [IDL.Vec(StoreCommentPublic)],
        ['query'],
      ),
    'loginArtist' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'loginCustomer' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'logoutArtist' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'logoutCustomer' : IDL.Func([IDL.Text], [], []),
    'notifyArtistJoined' : IDL.Func([IDL.Text], [], []),
    'notifyNewComment' : IDL.Func([ArtistId, IDL.Text], [], []),
    'notifyNewSale' : IDL.Func([ArtistId, IDL.Text], [], []),
    'notifyTrackUploaded' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'publishTrack' : IDL.Func(
        [IDL.Text, TrackId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'requestPayout' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : PayoutId, 'err' : IDL.Text })],
        [],
      ),
    'resetPINWithSecurityAnswer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'saveBankingInfo' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'searchTracks' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TrackMetadataPublic)],
        ['query'],
      ),
    'setArtistSecurityQuestion' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'setStripeConfiguration' : IDL.Func(
        [IDL.Text, StripeConfiguration],
        [],
        [],
      ),
    'signupArtist' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : ArtistProfilePublic, 'err' : IDL.Text })],
        [],
      ),
    'signupCustomer' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text })],
        [],
      ),
    'subscribeToMailingList' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unlikeArtistStore' : IDL.Func([IDL.Text, IDL.Text], [LikeResult], []),
    'unlikeTrack' : IDL.Func([IDL.Nat, IDL.Text], [LikeResult], []),
    'unpublishTrack' : IDL.Func(
        [IDL.Text, TrackId],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateArtistProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateArtistSocialLinks' : IDL.Func(
        [IDL.Text, ArtistSocialLinks],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'updateTrackMetadata' : IDL.Func(
        [
          IDL.Text,
          TrackId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'uploadTrack' : IDL.Func(
        [IDL.Text, TrackUploadInput],
        [IDL.Variant({ 'ok' : TrackId, 'err' : IDL.Text })],
        [],
      ),
    'validateCustomerSession' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'validateSession' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : ArtistId, 'err' : IDL.Text })],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };